### ISSUE TITLE
Rainbow and Sitecore 9

### ISSUE THREAD

**Issue by csoler46** [SitecoreUnicorn/Rainbow#23]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
I'm working in a solution based on Sitecore 8.1 and I am trying to upgrade to Sitecore 9. In the Analysis process, I receive several warnings of Rainbow, for example:

```
<shortdescription>Type Rainbow.Settings.RainbowSitecoreSettings from assembly Rainbow uses the type that has got breaking changes.</shortdescription>

<description>The type Sitecore.Configuration.Settings defined in assmebly Sitecore.Kernel has got breaking changes. Custom type Rainbow.Settings.RainbowSitecoreSettings defined in assembly Rainbow uses the changed type in System.Int32 get_SfsSerializationFolderPathMaxLength() and might be affected.</description>
```

Is Rainbow compatible with Sitecore 9? 

If yes, any reason why we are receiving these warnings? How we could avoid them?

In case we cannot overcome this we will remove Unicorn from our solution, install Sitecore 9 and then install Unicorn again but we would really prefer to solve this issue first.

**What is the expected behavior?**

There are no warnings in the Analysis result in the Update Installation Wizard

**Please mention your Sitecore version, Rainbow version, and if also using Unicorn, your version of that too.**

Sitecore 8.1
Unicorn 4.0.3
Rainbow 2.0.0

**Comment by kamsar** [comment]
Yes it is compatible with Sitecore 9.
________________________________

**Comment by cassidydotdk** [comment]
It's just a warning. As it says; "it might be affected". Key here is "might". I currently run and test Unicorn and Rainbow on Sitecore 9 without issue.
