### ISSUE TITLE
Unicorn API for Reserialize

### ISSUE THREAD

**Issue by vikashinchennai** [SitecoreUnicorn/Rainbow#28]
What is the API to call to perform unicorn reserialization??

**Comment by cassidydotdk** [comment]
... What do you mean?

**Comment by vikashinchennai** [comment]
I am looking for the api that can perform reserialization, currently the
api has o ly sync.
Can you please add that feature

**Comment by kamsar** [comment]
It already exists; you can change the `verb` to reserialize: https://github.com/SitecoreUnicorn/Unicorn/blob/dadad3f7e7d69fc2e54eb3732fa3951693545045/doc/PowerShell%20Remote%20Scripting/Unicorn.psm1#L16
