### ISSUE TITLE
Sync Both Master and Web Database

### ISSUE THREAD

**Issue by vikashinchennai** [SitecoreUnicorn/Rainbow#29]
What are the changes we need to make inorder to sync Both master and web database by default.
I will be calling the unicorn sync API command to sync and reserialize both the database on regular basics for backup.
Please provide that feature. in UI it shows checkbox to select the Database, but i want both the be selected by default.

**Comment by cassidydotdk** [comment]
Databases are selected in your predicates in your configuration. If you need to serialise both "master" and "web", make a predicate for both.

Because of this, a checkbox in the UI will not be an option.
