### ISSUE TITLE
DefaultDeserializer resets fields which are excluded in fieldFilter

### ISSUE THREAD

**Issue by NaibafCH** [SitecoreUnicorn/Rainbow#30]
**Do you want to request a *feature* or report a *bug*?**

Unknown

**What is the current behavior?**

I've excluded the Sitecore field "__Security" in the `<fieldFilter>` element of my Unicorn configuration. However, the field still gets reset during Sync when other fields of the same item have changed. This behaviour is somewhat described [here](https://github.com/SitecoreUnicorn/Unicorn/blob/master/README.md#field-filter), but it also states that the field should be "effectilvely ignored", which it is not. Therefore I'm not sure if this is a bug...

**If the current behavior is a bug, please provide the steps to reproduce.**

- Exclude a field in the `<fieldFilter>` element of your configuration (e.g. __Security)
- Change any value in another field in one of the serialized items. This way, the excluded field should be removed from the serialized item's file.
- Deserialize

**What is the expected behavior?**

Since I've excluded the field from Unicorn, I would expect this field to be completely ignored during serialization and deserialization.
I've added the necessary changes to the DefaultDeserializer including a unit test which illustrates this behaviour here: https://github.com/NaibafCH/Rainbow/commit/9e6a352db5460bff866b91ce933ff2bded263bf3

**Please mention your Sitecore version, Rainbow version, and if also using Unicorn, your version of that too.**

Sitecore: 9.0 Update-2
Rainbow: 2.0.0
Unicorn: 4.0.3

**Comment by cassidydotdk** [comment]
Have you verified this behaviour against `2.0.6-pre6`?  Quite a number of fixes related to field handling and field resetting since `2.0.0` was released.

**Comment by NaibafCH** [comment]
I've updated Rainbow to `2.0.6-pre6` in my Sitecore instance. Unfortunately, the behaviour is still the same. I also merged the develop branch into my own branch and tested the behaviour there.

**Comment by cassidydotdk** [comment]
Can you PR this? :-)

**Comment by cassidydotdk** [comment]
Fixed by the PR. Bug has been around for "quite a while", but since the default filter concerns fields that no-one really cares (much) about, it has gone unnoticed. Thanks for the PR :-)

**Comment by cassidydotdk** [comment]
https://github.com/SitecoreUnicorn/Rainbow/releases/tag/2.0.6-pre7
